module project.template {
    requires javafx.fxml;
    requires javafx.controls;

    requires AuthLib;
    requires guru.nidi.graphviz;
    requires gs.core;
    requires jdk.jshell;
    requires org.apache.commons.lang3;
    requires java.sql;
    requires gs.ui.swing;
    requires javafx.swing;
    requires svgSalamander;
    requires org.slf4j;

    opens pt.ipp.isep.dei to javafx.fxml;
    opens pt.ipp.isep.dei.controller.authorization to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.authorization to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.menu to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.message to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.map to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.InitializeSimulation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated.AddStation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated.ShowStation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated.RemoveStation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated.EditStation to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated.BuyCarriage to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated.BuyLocomotive to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.CreateRailwayLine to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated.ViewLocomotive to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.RemoveRailwayLine to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.ShowRailwayLine to javafx.fxml;
    opens pt.ipp.isep.dei.controller.map to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated.ViewCarriages to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.UpgradeRailwayLine to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RouteRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RouteRelated.CreateRoute to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain.Construct to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain.View to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.RouteRelated.ManageRoute to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.houseBlock to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.FinancialResult to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.industry to javafx.fxml;
    opens pt.ipp.isep.dei.ui.gui.simulation.StationRelated.EditStation.EditName to javafx.fxml;

    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain.View to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain.Construct to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.ConstructTrain to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated.ViewCarriages to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated.ViewLocomotive to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei;
    exports pt.ipp.isep.dei.ui.console.menu to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.authorization to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.menu to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.message to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.map;
    exports pt.ipp.isep.dei.ui.gui.simulation.InitializeSimulation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated.AddStation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated.ShowStation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated.RemoveStation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated.EditStation to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated.BuyCarriage to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.LocomotiveRelated.BuyLocomotive to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.CreateRailwayLine to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.RemoveRailwayLine to javafx.fxml;
    exports pt.ipp.isep.dei.controller.map to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.ShowRailwayLine;
    exports pt.ipp.isep.dei.ui.gui.simulation.RailwayRelated.UpgradeRailwayLine to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.simulation.RouteRelated to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.simulation.RouteRelated.CreateRoute to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.simulation.TrainRelated.CarriageRelated to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.RouteRelated.ManageRoute to javafx.fxml;
    exports pt.ipp.isep.dei.ui.gui.simulation.StationRelated.EditStation.EditName to javafx.fxml, javafx.graphics;
    exports pt.ipp.isep.dei.ui.gui.simulation.FinancialResult;
    exports pt.ipp.isep.dei.ui.gui.industry;
    exports pt.ipp.isep.dei.ui.gui.houseBlock to javafx.fxml, javafx.graphics;
}
