@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle
hide methods

title Domain Model

' ============= CLASS's =============

class Simulator {
    status: Boolean
    timeOfSimulation: Integer
}

class User {
    identifier: Integer
}

class Player {
    username: Text
    password: Text
}

class Editor {
    username: Text
    password: Text
}

class Map {
   name: Text
}

class Scenario {
  scenarioType: Text
  simulationPeriod: Integer
}

class HistoricalEvent {
    name: Text
    startDate: Date
    endDate: Date
    temporalRestrictions: Map
}

class Train {
    name: Text
    startYearOperation: Integer
    acquisitionPrice: Decimal
}

class Locomotive {
    name: Text
    power: Decimal
    acceleration: Decimal
    topSpeed: Decimal
    startYearOperation: Integer
    acquisitionPrice: Decimal
}

class Carriage {
    name: Text
    startYearOperation: Integer
}

class Route {
    name: Text
    routeType: Text
}

class Cargo {
    cargoType: Text
}

class Fuel {
  fuelType: Type
}

class Station {
  name: Text
  constructionCosts: Decimal
  stationType: Type
}

class Building {
  name: Text
  cost: Decimal
  requiredLevel: Integer
  buildingType: Type
}

class Industry {
   name: Text
   industryType: Type
}

class City {
   name: Text
   houseBlocks: Integer
}

class Size {
   width: Integer
   height: Integer
}

class Position {
   Xposition: Integer
   Yposition: Integer
}

' ============= INTERFACE's =============

interface FuelType {
    Steam
    Diesel
    Electricity
}

interface StationType {
    Depots
    Stations
    Terminals
}

interface BuildingType {
    Telegraph
    Coffee
    Customs
    PostOffice
    Hotel
    Silo
    LiquidStorage
}

interface IndustryType {
    PrimarySectorIndustry
    TransformingIndustry
    MixedIndustry
}

' ============ RELATIONSHIP's ============

'Simulator connections
Simulator "*" -- "*" Industry : has >
Simulator "*" -- "*" City : has >
Simulator "*" -- "1" Map : has >
Simulator "*" -- "1" Scenario : has >
Simulator "*" -- "*" Train : has >
Simulator "*" -- "*" Station : has >
Simulator "*" -- "*" Building : has >
Simulator "*" -- "*" Route : has >
Simulator "*" -- "*" Cargo : generate >
Simulator "*" -- "*" HistoricalEvent : has >
Simulator "*" -- "*" Locomotive : has >
Simulator "*" -- "*" Carriage : has >
Simulator "0,1" -- "0,1" Player : create/plays <

'User connections
User "1" -- "*" Player : is type of <
User "1" -- "1" Editor : is type of <

'Player connections
Player "1" -- "1" Simulator : start/pause >
Player "1" -- "*" Station : build / manages >
Player "1" -- "*" Train : owns >
Player "1" -- "*" Building : upgrades >
Player "1" -- "*" Map : has >
Player "1" - "*" Route : create >
Player "1" -- "*" Carriage: owns >
Player "1" -- "*" Locomotive: buy / owns >

'Editor connections
Editor "1" -- "*" Industry : adds >
Editor "1" -- "*" City : adds >
Editor "1" -- "1..*" Map : creates / edits >
Editor "1" -- "*" Scenario : creates / edits >

'Map connections
Map "*" -- "1" Size : has >
Map "*" -- "*" Station : has >
Map "*" -- "*" City : has >
Map "*" -- "*" Scenario : has >
Map "*" -- "*" Industry : has >
Map "*" -- "1..*" Position : has >

'Scenario connections
Scenario "*" -- "*" HistoricalEvent : has >
Scenario "*" -- "*" Locomotive: filter the possible >

'HistoricalEvent connections
HistoricalEvent "*" -- "*" City : affects >
HistoricalEvent "*" -- "*" Industry : disrupts >

'Train connections
Train "0,1" -- "*" Cargo : has >
Train "*" -- "1" Fuel : moves with >
Train "0,1" -- "1,2" Locomotive : consists of >
Train "0,1" -- "1..*" Carriage : consists of >
Train "*" -- "1" Route : assigned to >
Train "0,1" -- "*" Position : has >

'route connections
Route "*" -- "*" Cargo : assigned to >
Route "*" -- "2..*" Station : goes through >
Route "*" -- "*" City : connects >

'Fuel connections
Fuel "*" -- "1" FuelType : has >
Fuel "1" -- "*" Locomotive : powers >

'Station connections
Station "*" -- "*" Cargo : assigned to >
Station "*" -- "1" StationType : has >
Station "1" -- "1..*" Building : can be upgraded with >
Station "0,1" -- "1" Position : has >
Station "*" -- "1" Size : has >

'Building connections
Building "*" -- "1" BuildingType : has >

'Industry connections
Industry "0,1" -- "1" Position : has >
Industry "*" -- "1" IndustryType : has >
Industry "*" -- "*" Cargo : produces >

'City connections
City "0,1" -- "1" Position : has >
City "*" -- "*" Cargo : demands >

@enduml